"""empty message

Revision ID: 1c34b55daead
Revises: 
Create Date: 2024-03-27 15:34:28.532943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c34b55daead'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=True),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('borrowed_on', sa.String(), nullable=False),
    sa.Column('fee_per_day', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_table.id'], name=op.f('fk_transaction_table_book_id_book_table')),
    sa.ForeignKeyConstraint(['member_id'], ['member_table.id'], name=op.f('fk_transaction_table_member_id_member_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_table')
    op.drop_table('member_table')
    op.drop_table('book_table')
    # ### end Alembic commands ###
